-- Run this SQL in your Supabase SQL Editor to create the tables.
-- You can find the SQL Editor in the left sidebar of your Supabase dashboard (represented by a query symbol '>_').

-- 1. Create Bookings Table
CREATE TABLE IF NOT EXISTS public.bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NOT NULL,
    service TEXT NOT NULL,
    preferred_date DATE,
    message TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Create Feedback Table
CREATE TABLE IF NOT EXISTS public.feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    email TEXT NOT NULL,
    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Enable Row Level Security (RLS) for security
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.feedback ENABLE ROW LEVEL SECURITY;

-- 4. Create Policies to allow anonymous public inserts (so public visitors can submit forms)
-- Allow public visitors to insert data into bookings
CREATE POLICY "Allow public inserts on bookings" 
ON public.bookings 
FOR INSERT 
WITH CHECK (true);

-- Allow public visitors to insert data into feedback
CREATE POLICY "Allow public inserts on feedback" 
ON public.feedback 
FOR INSERT 
WITH CHECK (true);

-- Optional: Allow public to read feedback if you want to display it on the site later
CREATE POLICY "Allow public reads on feedback" 
ON public.feedback 
FOR SELECT 
USING (true);
